### ISSUE TITLE
Personal info edit not working

### ISSUE THREAD

**Issue by acatanyg** [nachoparker/nextcloud-raspbian-generator#11]
It is not possible to save the personal infos after edit.

NextCloudPi 11.0.3 & Raspberry Pi 3

**Comment by nachoparker** [comment]
I tested and I could replicate this on NextCloud 12

I found this issue and sure enough, setting the correct time worked for me.

https://github.com/nextcloud/server/issues/4533

Please, check the date on your Raspberry Pi

**Comment by acatanyg** [comment]
Thank you! I will test it next week.

Toni Catany Gelabert
