### ISSUE TITLE
Removing old kernel modules from packaged release

### ISSUE THREAD

**Issue by Dikay900** [nachoparker/nextcloud-raspbian-generator#3]
You can easily remove old kernel modules from /lib/modules/ which will reduce the image by ~150MB since you built and installed your own kernel.

```
uname -r
4.9.13-v7+
```

Thanks for this image and your work on this.

**Comment by nachoparker** [comment]
thanks for the suggestion. I will have a look at this for the next big release

**Comment by nachoparker** [comment]
implemented https://github.com/nachoparker/nextcloud-raspbian-generator/commit/40047afd4ee43bebb2411adb97d3a9b816159bad

thanks
