### ISSUE TITLE
Not able to SSH to 11.0.3 image

### ISSUE THREAD

**Issue by paarsand** [nachoparker/nextcloud-raspbian-generator#8]
I loaded up 11.0.3 image on my pi, it works great, now got everything running.

SSH is not working, the pi is not accepting the connection.

**Comment by nachoparker** [comment]
SSH is disabled by default for security reasons. This is the same as raspbian. 

You  can enable it with

sudo raspi-config 



I am on vacation for two weeks so I don't have constant connectivity

On April 29, 2017 8:41:01 AM GMT+02:00, paarsand <notifications@github.com> wrote:
>I loaded up 11.0.3 image on my pi, it works great, now got everything
>running.
>
>SSH is not working, the pi is not accepting the connection.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nachoparker/nextcloud-raspbian-generator/issues/8

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nachoparker** [comment]
I will close this now. Please reopen if you find another issue with SSH

**Comment by nachoparker** [comment]
update: you can also create an empty file called `ssh` on the boot partition of the SD card and SSH will be enabled automatically.
