### ISSUE TITLE
letsencrypt

### ISSUE THREAD

**Issue by drible79** [nachoparker/nextcloud-raspbian-generator#9]
I have just completed a fresh install and am trying to install letsencrypt from the setup utility and I get the following error message

Configuring letsencrypt
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for mycloud.ownyourbits.com
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. mycloud.ownyourbits.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: NXDOMAIN looking up A for mycloud.ownyourbits.com

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: mycloud.ownyourbits.com
   Type:   connection
   Detail: DNS problem: NXDOMAIN looking up A for
   mycloud.ownyourbits.com

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

**Comment by nachoparker** [comment]
Hello, that URL mycloud.com is an example. You need to register a domain. Please read the website for instructions. Look for unos one 

DDNS with no-ip

I am on vacation for two weeks so I don't have constant connectivity

On April 29, 2017 10:21:43 PM GMT+02:00, drible79 <notifications@github.com> wrote:
>I have just completed a fresh install and am trying to install
>letsencrypt from the setup utility and I get the following error
>message
>
>Configuring letsencrypt
>Saving debug log to /var/log/letsencrypt/letsencrypt.log
>Obtaining a new certificate
>Performing the following challenges:
>tls-sni-01 challenge for mycloud.ownyourbits.com
>Waiting for verification...
>Cleaning up challenges
>Failed authorization procedure. mycloud.ownyourbits.com (tls-sni-01):
>urn:acme:error:connection :: The server could not connect to the client
>to verify the domain :: DNS problem: NXDOMAIN looking up A for
>mycloud.ownyourbits.com
>
>IMPORTANT NOTES:
> - The following errors were reported by the server:
>
>   Domain: mycloud.ownyourbits.com
>   Type:   connection
>   Detail: DNS problem: NXDOMAIN looking up A for
>   mycloud.ownyourbits.com
>
>   To fix these errors, please make sure that your domain name was
>   entered correctly and the DNS A record(s) for that domain
>   contain(s) the right IP address. Additionally, please check that
>   your computer has a publicly routable IP address and that no
>   firewalls are preventing the server from communicating with the
>   client. If you're using the webroot plugin, you should also verify
>   that you are serving files from the webroot path you provided.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nachoparker/nextcloud-raspbian-generator/issues/9

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
